openapi: 3.0.0
info:
  title: Jeff's API
  version: 1.0.0
paths:
  /testing:
    get:
      summary: Provides a Test
      responses:
        '200':
          description: A test confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Testing Prism
